In [1]:
import numpy as np

a =np.array([[0, 3, 1],
             [3, 7, 5],
             [6, 4, 8]])

b = [10, 5, 11]

print("add_array=\n",np.add(a,b))
print("subtract_array=\n",np.subtract(a,b))
print("multiply_array=\n",np.multiply(a,b))
print("divide_array=\n",np.divide(a,b))

add_array=
 [[10  8 12]
 [13 12 16]
 [16  9 19]]
subtract_array=
 [[-10  -2 -10]
 [ -7   2  -6]
 [ -4  -1  -3]]
multiply_array=
 [[ 0 15 11]
 [30 35 55]
 [60 20 88]]
divide_array=
 [[0.         0.6        0.09090909]
 [0.3        1.4        0.45454545]
 [0.6        0.8        0.72727273]]
