In [2]:
import numpy as np

a = [7,3,4,5,1]
b = [3,4,5,6,7]

print(np.remainder(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.reciprocal(a))


[1 3 4 5 1]
[  343    81  1024 15625     1]
[1 3 4 5 1]
[0 0 0 0 1]
