In [3]:
import numpy as np
arr_2D =np.array([[1 , 2, 3], [4, 5, 6]])

new_arr_2D =np.reshape(arr_2D , (3, 2))

arr_1D =np.reshape(arr_2D ,newshape=(6, ))

print("array 2D:\n",arr_2D , arr_2D.shape )
print("new array 2D :\n",new_arr_2D, new_arr_2D.shape)
print("array 1D:\n",arr_1D, arr_1D.shape)

array 2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
new array 2D :
 [[1 2]
 [3 4]
 [5 6]] (3, 2)
array 1D:
 [1 2 3 4 5 6] (6,)


C:\Users\LAPTOP AK\AppData\Local\Temp\ipykernel_5876\1513098475.py:6: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  arr_1D =np.reshape(arr_2D ,newshape=(6, ))
